model:
  name: "openai/clip-vit-base-patch32"
  num_layers: 12

datasets:
  root: "./data/datasets.py"
  batch_size: 2
  image_size: 224
  num_workers: 0
  pin_memory: False

train:
  name: "adamw" #name should be in "adamw", "sgd", "adam"
  lr: 3e-4
  weight_decay : 0.05
  max_epoch: 50
  patience: 3
  epsilon: 1e-4
  r: 2